//! Preflight pipeline composition for orchestrator iterations.
//!
//! Composes the steps that run before each agent invocation into a typed
//! pipeline with deterministic wrappers around LLM outputs:
//!
//! 1. **Context packing** — build WorkPacket from issue + error state
//! 2. **Knowledge enrichment** — query NotebookLM for architectural context / error playbooks
//! 3. **Plan generation** (optional) — LLM-generated plan validated by schema
//! 4. **Verifier hint staging** — extract actionable hints from last verifier report
//! 5. **Prompt assembly** — format the final agent prompt
//!
//! Each stage is a pure function from `PreflightContext → PreflightContext`,
//! making the pipeline testable and deterministic (LLM stages wrap outputs
//! in validated schemas or discard on failure).

use coordination::{ContextPacker, SwarmTier, VerifierReport, WorkPacket};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use tracing::{info, warn};

use crate::harness::HarnessPolicy;
use crate::notebook_bridge::KnowledgeBase;
use crate::pipeline_config::PipelineConfig;

/// Context threaded through the preflight pipeline.
///
/// Stages read from and extend this struct. The final state
/// is consumed by the orchestrator to build the agent prompt.
#[derive(Debug, Clone)]
pub struct PreflightContext {
    /// The work packet assembled by context packing.
    pub packet: WorkPacket,
    /// Explicit runtime harness policy for this packet.
    pub harness: HarnessPolicy,
    /// Optional plan generated by the plan stage.
    pub plan: Option<ImplementationPlan>,
    /// Verifier hints extracted from the last report.
    pub verifier_hints: Vec<VerifierHint>,
    /// Whether knowledge enrichment succeeded.
    pub kb_enriched: bool,
    /// Stages that ran (for diagnostics).
    pub stages_run: Vec<String>,
    /// Acceptance criteria generated by the planner stage.
    ///
    /// When present, both the coder and reviewer receive these criteria
    /// as a shared "definition of done". Generated once per issue on the
    /// initial iteration and carried forward through retries.
    pub acceptance_criteria: Option<AcceptanceCriteria>,
}

/// Observable conditions that define "done" for this sprint.
///
/// Generated by the fast-tier planner from the issue description and
/// injected into both coder and reviewer prompts. This aligns generator
/// and evaluator on shared expectations before any code is written.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct AcceptanceCriteria {
    /// Functional requirements: observable behaviours the implementation must have.
    /// e.g., "cargo test -p coordination passes", "fn parse_error() returns Err for invalid input"
    pub functional: Vec<String>,
    /// Non-functional constraints that apply to all code regardless of task.
    /// e.g., "no new clippy warnings", "no bare unwrap() on fallible operations"
    pub non_functional: Vec<String>,
    /// Explicitly excluded scope to prevent scope creep.
    pub out_of_scope: Vec<String>,
}

impl AcceptanceCriteria {
    /// Render the criteria as a prompt section.
    ///
    /// Injected into both coder and reviewer prompts so they share
    /// the same "definition of done".
    pub fn to_prompt_section(&self) -> String {
        let mut out = String::from("## Acceptance Criteria\n");
        out.push_str("The implementation is DONE when ALL of the following are true:\n\n");

        if !self.functional.is_empty() {
            out.push_str("**Functional:**\n");
            for f in &self.functional {
                out.push_str(&format!("- {f}\n"));
            }
            out.push('\n');
        }

        if !self.non_functional.is_empty() {
            out.push_str("**Non-functional (always apply):**\n");
            for nf in &self.non_functional {
                out.push_str(&format!("- {nf}\n"));
            }
            out.push('\n');
        }

        if !self.out_of_scope.is_empty() {
            out.push_str("**Out of scope (do NOT do this):**\n");
            for item in &self.out_of_scope {
                out.push_str(&format!("- {item}\n"));
            }
            out.push('\n');
        }

        out
    }
}

/// A validated implementation plan from the plan generation stage.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct ImplementationPlan {
    /// High-level approach description.
    pub approach: String,
    /// Ordered steps to implement.
    pub steps: Vec<PlanStep>,
    /// Files expected to be modified.
    pub target_files: Vec<String>,
    /// Estimated risk level (low/medium/high).
    pub risk: PlanRisk,
}

/// A single step in an implementation plan.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct PlanStep {
    /// What to do.
    pub description: String,
    /// File to modify (if known).
    pub file: Option<String>,
}

/// Risk assessment for a plan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum PlanRisk {
    Low,
    Medium,
    High,
}

// ── Architect/Editor Pattern ─────────────────────────────────────────────────
//
// The Architect (cloud model) produces an ArchitectPlan with exact SEARCH/REPLACE
// edit blocks. The Editor (local 27B) applies them mechanically. This turns complex
// tasks into mechanical tasks from the local model's perspective.
//
// Flow: Cloud Architect → ArchitectPlan JSON → Local Editor applies edits
//
// Based on Aider's Architect/Editor pattern: the slow model's job is to translate
// a plan into code, not to reason about the codebase.

/// An architect plan with exact SEARCH/REPLACE edit blocks.
///
/// Unlike `ImplementationPlan` (which has vague `PlanStep` descriptions),
/// this contains the exact code changes to make. The Editor applies them
/// without needing to understand the codebase.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct ArchitectPlan {
    /// High-level summary of what this plan does and why.
    pub summary: String,
    /// Ordered list of edits to apply. Each edit targets one file.
    pub edits: Vec<ArchitectEdit>,
    /// Files that will be modified (derived from edits).
    pub target_files: Vec<String>,
}

/// A single SEARCH/REPLACE edit block produced by the Architect.
///
/// Contains the exact old code to find and the exact new code to replace it with.
/// The Editor applies this by calling `edit_file(path, old_content, new_content)`.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct ArchitectEdit {
    /// File to modify (relative to worktree root).
    pub file: String,
    /// Exact code to search for in the file. Must match file content exactly.
    /// Include 3-5 lines of surrounding context for uniqueness.
    pub search: String,
    /// Exact replacement code. This replaces the `search` block verbatim.
    pub replace: String,
    /// Brief description of what this edit does (for the Editor's context).
    pub description: String,
}

impl ArchitectPlan {
    /// Validate the plan: at least one edit, all edits have non-empty search/replace.
    pub fn validate(&self) -> Result<(), String> {
        if self.edits.is_empty() {
            return Err("Architect plan has no edits".into());
        }
        for (i, edit) in self.edits.iter().enumerate() {
            if edit.file.is_empty() {
                return Err(format!("Edit {i}: missing file path"));
            }
            if edit.search.is_empty() {
                return Err(format!("Edit {i}: empty search block"));
            }
            if edit.replace.is_empty() && !edit.description.contains("delete") {
                return Err(format!(
                    "Edit {i}: empty replace block (use 'delete' in description if intentional)"
                ));
            }
            if edit.search == edit.replace {
                return Err(format!(
                    "Edit {i}: search and replace are identical (no-op)"
                ));
            }
        }
        Ok(())
    }

    /// Format the plan as instructions for the Editor agent.
    pub fn to_editor_prompt(&self) -> String {
        let mut prompt = format!("## Architect Plan: {}\n\n", self.summary);
        prompt.push_str(&format!(
            "Apply these {} edits in order:\n\n",
            self.edits.len()
        ));

        for (i, edit) in self.edits.iter().enumerate() {
            prompt.push_str(&format!(
                "### Edit {} of {}: {}\n",
                i + 1,
                self.edits.len(),
                edit.description
            ));
            prompt.push_str(&format!("**File:** `{}`\n\n", edit.file));
            prompt.push_str("**SEARCH** (find this exact text):\n```\n");
            prompt.push_str(&edit.search);
            prompt.push_str("\n```\n\n**REPLACE** (replace with this):\n```\n");
            prompt.push_str(&edit.replace);
            prompt.push_str("\n```\n\n");
        }

        prompt.push_str("**Instructions:** For each edit above, call `edit_file` with:\n");
        prompt.push_str("- `path`: the file path shown\n");
        prompt.push_str("- `old_content`: the SEARCH block (exact text)\n");
        prompt.push_str("- `new_content`: the REPLACE block (exact text)\n\n");
        prompt.push_str("Apply edits in order. After ALL edits are applied, you are DONE.\n");

        prompt
    }
}

/// Directly apply an `ArchitectPlan` without invoking an LLM Editor.
///
/// For each edit, reads the target file, performs str_replace (exact match first,
/// fuzzy fallback), and writes the result. Returns a summary of applied/failed edits.
///
/// This is the "direct" editor mode (`SWARM_EDITOR_MODE=direct`): zero LLM rounds
/// for the edit phase, compared to 10-15 agentic rounds in the default mode.
/// All byte-offsets where `needle` occurs in `haystack` (overlapping allowed).
fn find_all_offsets(haystack: &str, needle: &str) -> Vec<usize> {
    let mut offsets = Vec::new();
    let mut start = 0;
    while let Some(pos) = haystack[start..].find(needle) {
        offsets.push(start + pos);
        start += pos + 1;
    }
    offsets
}

fn replace_at_offset(content: &str, start: usize, search_len: usize, replace: &str) -> String {
    let end = start + search_len;
    let mut result = String::with_capacity(content.len() - search_len + replace.len());
    result.push_str(&content[..start]);
    result.push_str(replace);
    result.push_str(&content[end..]);
    result
}

fn normalize_whitespace(text: &str) -> Vec<String> {
    text.lines()
        .map(|l| l.split_whitespace().collect::<Vec<_>>().join(" "))
        .collect()
}

/// Whitespace-normalized fuzzy match (patch_tool tier 4 behaviour).
/// Returns the new content if exactly one fuzzy match is found.
fn fuzzy_replace(content: &str, search: &str, replace: &str) -> Result<String, usize> {
    let norm_search = normalize_whitespace(search);
    let content_lines: Vec<&str> = content.lines().collect();
    let norm_content = normalize_whitespace(content);

    let window = norm_search.len();
    let scan_end = content_lines.len().saturating_sub(window.saturating_sub(1));
    let matches: Vec<usize> = (0..scan_end)
        .filter(|&j| norm_content[j..j + window] == norm_search[..])
        .collect();

    if matches.len() != 1 {
        return Err(matches.len());
    }
    let match_start = matches[0];
    let match_end = match_start + window;
    let mut result = String::new();
    for (idx, line) in content_lines.iter().enumerate() {
        if idx == match_start {
            result.push_str(replace);
            result.push('\n');
        } else if !(idx >= match_start && idx < match_end) {
            result.push_str(line);
            result.push('\n');
        }
    }
    if !content.ends_with('\n') && result.ends_with('\n') {
        result.pop();
    }
    Ok(result)
}

/// Apply a single edit to the given file, returning the new content or an error reason.
fn apply_single_edit(edit: &ArchitectEdit, wt_path: &std::path::Path) -> Result<String, String> {
    let full_path = wt_path.join(&edit.file);
    let content = std::fs::read_to_string(&full_path)
        .map_err(|e| format!("cannot read {}: {e}", edit.file))?;

    let occurrences = find_all_offsets(&content, &edit.search);
    let new_content = match occurrences.len() {
        1 => replace_at_offset(&content, occurrences[0], edit.search.len(), &edit.replace),
        0 => fuzzy_replace(&content, &edit.search, &edit.replace).map_err(|fuzzy_n| {
            format!(
                "search block not found in {} (0 exact, {fuzzy_n} fuzzy matches)",
                edit.file
            )
        })?,
        n => {
            return Err(format!(
                "search block matches {n} locations in {} — ambiguous",
                edit.file
            ))
        }
    };

    std::fs::write(&full_path, &new_content)
        .map_err(|e| format!("write failed for {}: {e}", edit.file))?;
    Ok(new_content)
}

pub fn direct_apply_plan(plan: &ArchitectPlan, wt_path: &std::path::Path) -> DirectApplyResult {
    let mut applied = Vec::new();
    let mut failed = Vec::new();

    for (i, edit) in plan.edits.iter().enumerate() {
        match apply_single_edit(edit, wt_path) {
            Ok(_) => {
                applied.push(format!("Edit {}: {} — {}", i + 1, edit.file, edit.description));
                info!(
                    file = %edit.file,
                    edit = i + 1,
                    total = plan.edits.len(),
                    "Direct editor: applied edit"
                );
            }
            Err(reason) => failed.push(format!("Edit {}: {reason}", i + 1)),
        }
    }
    DirectApplyResult { applied, failed }
}

/// Result of directly applying an `ArchitectPlan` without an LLM Editor.
#[derive(Debug, Clone)]
pub struct DirectApplyResult {
    /// Edits that were successfully applied.
    pub applied: Vec<String>,
    /// Edits that failed with reasons.
    pub failed: Vec<String>,
}

impl DirectApplyResult {
    /// Whether all edits were applied successfully.
    pub fn all_succeeded(&self) -> bool {
        self.failed.is_empty() && !self.applied.is_empty()
    }

    /// Format as a summary string for logging/display.
    pub fn summary(&self) -> String {
        let mut s = format!(
            "Direct editor: {}/{} edits applied",
            self.applied.len(),
            self.applied.len() + self.failed.len()
        );
        for f in &self.failed {
            s.push_str(&format!("\n  FAILED: {f}"));
        }
        s
    }
}

/// An actionable hint extracted from a verifier report.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerifierHint {
    /// Which gate produced this hint (fmt, clippy, check, test).
    pub gate: String,
    /// The actionable message.
    pub message: String,
    /// Optional file location.
    pub file: Option<String>,
    /// Optional line number.
    pub line: Option<usize>,
}

/// Configuration for the preflight pipeline.
#[derive(Debug, Clone)]
pub struct PreflightConfig {
    /// Whether to run the plan generation stage.
    pub enable_plan_generation: bool,
    /// Whether to run knowledge enrichment.
    pub enable_kb_enrichment: bool,
    /// Maximum number of verifier hints to stage.
    pub max_verifier_hints: usize,
    /// Maximum number of plan steps allowed (schema validation).
    pub max_plan_steps: usize,
}

impl Default for PreflightConfig {
    fn default() -> Self {
        Self {
            enable_plan_generation: false,
            enable_kb_enrichment: true,
            max_verifier_hints: 10,
            max_plan_steps: 15,
        }
    }
}

impl PreflightConfig {
    /// Build a `PreflightConfig` from a loaded [`PipelineConfig`].
    ///
    /// Maps TOML stage presence to the boolean gates that control which stages
    /// run. Stage names are matched by convention:
    /// - `plan_generation` or `plan` → `enable_plan_generation`
    /// - `knowledge_enrichment` → `enable_kb_enrichment`
    pub fn from_pipeline_config(cfg: &PipelineConfig) -> Self {
        let enable_plan_generation =
            cfg.stage("plan_generation").is_some() || cfg.stage("plan").is_some();
        let enable_kb_enrichment = cfg.stage("knowledge_enrichment").is_some();

        Self {
            enable_plan_generation,
            enable_kb_enrichment,
            max_verifier_hints: 10,
            max_plan_steps: 15,
        }
    }
}

/// Run the preflight pipeline for the initial iteration (no prior errors).
pub fn run_initial(
    wt_path: &std::path::Path,
    issue_id: &str,
    issue_title: &str,
    tier: SwarmTier,
    knowledge_base: Option<&dyn KnowledgeBase>,
    config: &PreflightConfig,
) -> PreflightContext {
    let packer = ContextPacker::new(wt_path, tier);
    let mut packet = packer.pack_initial(issue_id, issue_title);
    let harness = HarnessPolicy::derive(&packet, tier);
    harness.apply_to_packet(&mut packet);

    let mut ctx = PreflightContext {
        packet,
        harness,
        plan: None,
        verifier_hints: Vec::new(),
        kb_enriched: false,
        stages_run: vec!["context_packing".into(), "harness_policy".into()],
        acceptance_criteria: None,
    };

    // Blast-radius enrichment: if code-review-graph has been built, use it
    // to identify affected files and inject them into the work packet's
    // relevant_heuristics as localization context for the worker.
    ctx = stage_blast_radius_enrichment(ctx, wt_path);

    if config.enable_kb_enrichment {
        ctx = stage_knowledge_enrichment(ctx, issue_id, issue_title, None, knowledge_base);
    }

    ctx = stage_acceptance_criteria(ctx);

    // Re-derive harness policy now that enrichment stages may have mutated
    // ctx.packet (blast-radius and KB enrichment can add file_contexts,
    // relevant_heuristics, and failure_signals that affect the derived policy).
    let harness = HarnessPolicy::derive(&ctx.packet, tier);
    harness.apply_to_packet(&mut ctx.packet);
    ctx.harness = harness;

    ctx
}

/// Run the preflight pipeline driven by a TOML [`PipelineConfig`].
///
/// This is a config-driven wrapper around `run_initial`: it derives a
/// [`PreflightConfig`] from the loaded TOML stage registry and delegates
/// to the existing stage functions. Stages absent from the registry (or
/// disabled) are skipped; unknown stage names are logged and ignored.
///
/// The wrapper preserves full backward compatibility — callers that do not
/// have a `PipelineConfig` continue to use `run_initial` directly.
pub fn run_with_stage_config(
    wt_path: &std::path::Path,
    issue_id: &str,
    issue_title: &str,
    tier: SwarmTier,
    knowledge_base: Option<&dyn KnowledgeBase>,
    pipeline_cfg: &PipelineConfig,
) -> PreflightContext {
    let preflight_cfg = PreflightConfig::from_pipeline_config(pipeline_cfg);
    info!(
        pipeline = %pipeline_cfg.name(),
        enable_plan = preflight_cfg.enable_plan_generation,
        enable_kb = preflight_cfg.enable_kb_enrichment,
        "Running preflight pipeline from TOML stage registry"
    );
    run_initial(
        wt_path,
        issue_id,
        issue_title,
        tier,
        knowledge_base,
        &preflight_cfg,
    )
}

/// Stage: Enrich the work packet with blast-radius analysis from code-review-graph.
///
/// If a `.code-review-graph/` directory exists (graph has been built), runs the
/// `code-review-graph impact` command to find all files affected by the issue's
/// target files. Injects the results into `packet.relevant_heuristics` so the
/// worker knows which files to focus on.
///
/// Degrades gracefully: if the graph doesn't exist or the CLI fails, the stage
/// is skipped and the worker falls back to the existing file targeting heuristics.
fn stage_blast_radius_enrichment(
    mut ctx: PreflightContext,
    wt_path: &std::path::Path,
) -> PreflightContext {
    use crate::tools::blast_radius_tool::CRG_BIN;

    let graph_dir = wt_path.join(".code-review-graph");
    if !graph_dir.exists() {
        return ctx;
    }

    // Collect target files from the work packet's file_contexts
    let target_files: Vec<&str> = ctx
        .packet
        .file_contexts
        .iter()
        .filter(|fc| fc.priority <= 1) // Only high-priority (error/modified) files
        .map(|fc| fc.file.as_str())
        .collect();

    if target_files.is_empty() {
        return ctx;
    }

    let files_arg = target_files.join(",");

    // Run code-review-graph impact with a real 10s timeout.
    // Uses channel + recv_timeout (sync-safe) rather than the async run_crg()
    // helper, because this stage runs in a sync pipeline context.
    let wt = wt_path.to_path_buf();
    let tf: Vec<String> = target_files.iter().map(|s| s.to_string()).collect();
    let (tx, rx) = std::sync::mpsc::channel();
    std::thread::spawn(move || {
        let result = std::process::Command::new(CRG_BIN)
            .args([
                "impact",
                "--depth",
                "3",
                "--max-files",
                "20",
                "--json",
                "--",
            ])
            .args(&tf)
            .current_dir(&wt)
            .output();
        let _ = tx.send(result);
    });

    let output = match rx.recv_timeout(std::time::Duration::from_secs(10)) {
        Ok(result) => result,
        Err(_) => {
            warn!("Blast-radius enrichment timed out after 10s (non-fatal)");
            return ctx;
        }
    };

    match output {
        Ok(out) if out.status.success() => {
            let stdout = String::from_utf8_lossy(&out.stdout);
            if !stdout.trim().is_empty() {
                let hint = format!(
                    "## Blast Radius Analysis (code-review-graph)\n\
                     Changed files: {}\n\
                     Affected files and dependencies:\n{}",
                    files_arg,
                    stdout.trim()
                );
                ctx.packet.relevant_heuristics.push(hint);
                ctx.stages_run.push("blast_radius_enrichment".into());
                info!(
                    target_files = target_files.len(),
                    "Blast-radius enrichment completed"
                );
            }
        }
        Ok(out) => {
            let stderr = String::from_utf8_lossy(&out.stderr);
            warn!(
                error = %stderr.trim(),
                "Blast-radius enrichment failed (non-fatal)"
            );
        }
        Err(e) => {
            warn!(
                error = %e,
                "code-review-graph not available (non-fatal)"
            );
        }
    }

    ctx
}

/// Stage: Extract actionable hints from the last verifier report.
#[allow(dead_code)]
fn stage_verifier_hints(
    mut ctx: PreflightContext,
    report: &VerifierReport,
    max_hints: usize,
) -> PreflightContext {
    let mut hints = Vec::new();

    // Extract hints from each gate's stderr excerpt and parsed errors
    for gate in &report.gates {
        // First, extract from parsed errors (structured)
        for error in &gate.errors {
            hints.push(VerifierHint {
                gate: gate.gate.clone(),
                message: error.message.clone(),
                file: error.file.clone(),
                line: error.line,
            });
            if hints.len() >= max_hints {
                break;
            }
        }
        if hints.len() >= max_hints {
            break;
        }

        // Then, extract from raw stderr if available and no parsed errors
        if gate.errors.is_empty() {
            if let Some(ref stderr) = gate.stderr_excerpt {
                for line in stderr.lines().take(3) {
                    let trimmed = line.trim();
                    if trimmed.is_empty() || trimmed.len() < 5 {
                        continue;
                    }
                    let (file, line_num) = parse_file_line(trimmed);
                    hints.push(VerifierHint {
                        gate: gate.gate.clone(),
                        message: trimmed.to_string(),
                        file,
                        line: line_num,
                    });
                    if hints.len() >= max_hints {
                        break;
                    }
                }
            }
        }
        if hints.len() >= max_hints {
            break;
        }
    }

    info!(
        hint_count = hints.len(),
        "Staged verifier hints for next iteration"
    );
    ctx.verifier_hints = hints;
    ctx.stages_run.push("verifier_hints".into());
    ctx
}

/// Stage: Enrich the work packet with knowledge base context.
fn stage_knowledge_enrichment(
    mut ctx: PreflightContext,
    issue_id: &str,
    issue_title: &str,
    last_report: Option<&VerifierReport>,
    knowledge_base: Option<&dyn KnowledgeBase>,
) -> PreflightContext {
    let Some(kb) = knowledge_base else {
        ctx.stages_run.push("kb_enrichment_skipped".into());
        return ctx;
    };

    // Query Project Brain for architectural context
    let brain_question =
        format!("What architectural context is relevant for: {issue_title}? Issue: {issue_id}");
    match kb.query("project_brain", &brain_question) {
        Ok(response) if !response.is_empty() => {
            ctx.packet.relevant_heuristics.push(response);
            ctx.kb_enriched = true;
            info!("Enriched packet with Project Brain context");
        }
        Ok(_) => {}
        Err(e) => {
            warn!(error = %e, "Project Brain query failed — continuing without");
        }
    }

    // On retries, also query Debugging KB for error patterns
    if let Some(report) = last_report {
        if !ctx.packet.failure_signals.is_empty() {
            let error_desc = ctx
                .packet
                .failure_signals
                .iter()
                .take(3)
                .map(|s| format!("{}: {}", s.category, s.message))
                .collect::<Vec<_>>()
                .join("; ");

            let gates_failed = report.gates_total.saturating_sub(report.gates_passed);
            let debug_question = format!(
                "Known fixes for these errors in {issue_id}: {error_desc}. \
                 Verifier had {} failure signals across {gates_failed} failed gates.",
                report.failure_signals.len(),
            );

            match kb.query("debugging_kb", &debug_question) {
                Ok(response) if !response.is_empty() => {
                    ctx.packet.relevant_playbooks.push(response);
                    ctx.kb_enriched = true;
                    info!("Enriched packet with Debugging KB playbook");
                }
                Ok(_) => {}
                Err(e) => {
                    warn!(error = %e, "Debugging KB query failed — continuing without");
                }
            }
        }
    }

    ctx.stages_run.push("kb_enrichment".into());
    ctx
}

/// Validate a raw plan string against the schema constraints.
///
/// Returns `Some(ImplementationPlan)` if valid, `None` if malformed (fail-closed).
pub fn validate_plan(raw: &str, max_steps: usize) -> Option<ImplementationPlan> {
    match serde_json::from_str::<ImplementationPlan>(raw) {
        Ok(plan) => {
            // Schema validation: enforce bounds
            if plan.steps.is_empty() {
                warn!("Plan validation failed: no steps");
                return None;
            }
            if plan.steps.len() > max_steps {
                warn!(
                    steps = plan.steps.len(),
                    max = max_steps,
                    "Plan validation failed: too many steps"
                );
                return None;
            }
            if plan.approach.trim().is_empty() {
                warn!("Plan validation failed: empty approach");
                return None;
            }
            Some(plan)
        }
        Err(e) => {
            warn!(error = %e, "Plan validation failed: malformed JSON");
            None
        }
    }
}

/// Stage: Derive acceptance criteria from the issue description.
///
/// Parses functional and non-functional requirements out of the objective text
/// without requiring an LLM call — heuristics are sufficient to bootstrap the
/// shared "definition of done" that aligns coder and reviewer.
///
/// The generated criteria are injected into `PreflightContext.acceptance_criteria`
/// and later rendered into both coder and reviewer prompts via
/// `AcceptanceCriteria::to_prompt_section()`.
pub fn stage_acceptance_criteria(mut ctx: PreflightContext) -> PreflightContext {
    let objective = ctx.packet.objective.clone();
    if objective.trim().is_empty() {
        ctx.stages_run.push("acceptance_criteria_skipped".into());
        return ctx;
    }

    let mut functional = Vec::new();
    let mut non_functional = Vec::new();
    let out_of_scope = Vec::new();

    // Derive functional criteria from the objective text.
    // Heuristics only; the sprint contract (when present) supersedes with
    // richer, negotiated criteria.
    let lower = objective.to_lowercase();

    if lower.contains("rust")
        || lower.contains("cargo")
        || lower.contains("crate")
        || lower.contains("fn ")
    {
        functional.push("cargo test -p swarm-agents passes with no new failures".to_string());
    } else {
        functional.push("all existing tests pass after the change".to_string());
    }

    if lower.contains("fix")
        || lower.contains("bug")
        || lower.contains("broken")
        || lower.contains("panic")
    {
        functional
            .push("the described issue no longer reproduces on the relevant input".to_string());
    }

    if lower.contains("add")
        || lower.contains("implement")
        || lower.contains("create")
        || lower.contains("support")
    {
        functional.push(
            "the new functionality is reachable from at least one code path (no dead code)"
                .to_string(),
        );
    }

    non_functional
        .push("no new clippy warnings introduced (cargo clippy -- -D warnings)".to_string());
    non_functional.push("no bare unwrap() calls added in non-test code".to_string());
    non_functional.push("no stub bodies (todo!(), unimplemented!(), empty return)".to_string());

    let criteria = AcceptanceCriteria {
        functional,
        non_functional,
        out_of_scope,
    };

    info!(
        functional_count = criteria.functional.len(),
        "Staged acceptance criteria"
    );
    ctx.acceptance_criteria = Some(criteria);
    ctx.stages_run.push("acceptance_criteria".into());
    ctx
}

/// Try to extract file path and line number from a compiler error line.
///
/// Handles patterns like:
/// - `error[E0308]: mismatched types --> src/lib.rs:42:5`
/// - `src/main.rs:10:3: warning: ...`
#[allow(dead_code)]
fn parse_file_line(line: &str) -> (Option<String>, Option<usize>) {
    // Pattern: "... --> file:line:col"
    if let Some(arrow_pos) = line.find("--> ") {
        let after = &line[arrow_pos + 4..];
        return parse_file_colon_line(after);
    }

    // Pattern: "file:line:col: ..."
    if let Some(colon_pos) = line.find(':') {
        let candidate = &line[..colon_pos];
        if candidate.contains('.') && !candidate.contains(' ') {
            return parse_file_colon_line(line);
        }
    }

    (None, None)
}

#[allow(dead_code)]
fn parse_file_colon_line(s: &str) -> (Option<String>, Option<usize>) {
    let parts: Vec<&str> = s.splitn(3, ':').collect();
    if parts.len() >= 2 {
        let file = parts[0].trim().to_string();
        let line = parts[1].trim().parse::<usize>().ok();
        if !file.is_empty() {
            return (Some(file), line);
        }
    }
    (None, None)
}

/// Append verifier hints to the work packet's failure signals or heuristics.
pub fn apply_hints_to_packet(packet: &mut WorkPacket, hints: &[VerifierHint]) {
    if hints.is_empty() {
        return;
    }

    let hint_block = hints
        .iter()
        .map(|h| {
            let loc = match (&h.file, h.line) {
                (Some(f), Some(l)) => format!(" ({f}:{l})"),
                (Some(f), None) => format!(" ({f})"),
                _ => String::new(),
            };
            format!("[{}]{}: {}", h.gate, loc, h.message)
        })
        .collect::<Vec<_>>()
        .join("\n");

    packet
        .relevant_heuristics
        .push(format!("## Verifier Hints\n{hint_block}"));
}

#[cfg(test)]
mod tests {
    use super::*;
    use coordination::SwarmTier;

    /// Construct a minimal WorkPacket for testing.
    fn test_work_packet() -> WorkPacket {
        WorkPacket {
            bead_id: "test-001".into(),
            branch: "test/branch".into(),
            checkpoint: "abc1234".into(),
            objective: "Test objective".into(),
            files_touched: vec![],
            key_symbols: vec![],
            file_contexts: vec![],
            verification_gates: vec![],
            failure_signals: vec![],
            constraints: vec![],
            iteration: 1,
            target_tier: SwarmTier::Worker,
            escalation_reason: None,
            error_history: vec![],
            previous_attempts: vec![],
            iteration_deltas: vec![],
            relevant_heuristics: vec![],
            relevant_playbooks: vec![],
            decisions: vec![],
            generated_at: chrono::Utc::now(),
            max_patch_loc: 150,
            delegation_chain: vec![],
            skill_hints: vec![],
            replay_hints: vec![],
            validator_feedback: vec![],
            change_contract: None,
            repo_map: None,
            failed_approach_summary: None,
            dependency_graph: None,
        }
    }

    #[test]
    fn test_preflight_config_defaults() {
        let config = PreflightConfig::default();
        assert!(!config.enable_plan_generation);
        assert!(config.enable_kb_enrichment);
        assert_eq!(config.max_verifier_hints, 10);
        assert_eq!(config.max_plan_steps, 15);
    }

    #[test]
    fn test_validate_plan_valid() {
        let raw = serde_json::to_string(&ImplementationPlan {
            approach: "Fix the borrow checker error".into(),
            steps: vec![PlanStep {
                description: "Add lifetime annotation".into(),
                file: Some("src/lib.rs".into()),
            }],
            target_files: vec!["src/lib.rs".into()],
            risk: PlanRisk::Low,
        })
        .unwrap();

        let plan = validate_plan(&raw, 15).unwrap();
        assert_eq!(plan.steps.len(), 1);
        assert_eq!(plan.risk, PlanRisk::Low);
    }

    #[test]
    fn test_validate_plan_empty_steps_rejected() {
        let raw = serde_json::to_string(&ImplementationPlan {
            approach: "Do nothing".into(),
            steps: vec![],
            target_files: vec![],
            risk: PlanRisk::Low,
        })
        .unwrap();

        assert!(validate_plan(&raw, 15).is_none());
    }

    #[test]
    fn test_validate_plan_too_many_steps_rejected() {
        let steps: Vec<PlanStep> = (0..20)
            .map(|i| PlanStep {
                description: format!("Step {i}"),
                file: None,
            })
            .collect();
        let raw = serde_json::to_string(&ImplementationPlan {
            approach: "Big plan".into(),
            steps,
            target_files: vec![],
            risk: PlanRisk::High,
        })
        .unwrap();

        assert!(validate_plan(&raw, 15).is_none());
    }

    #[test]
    fn test_validate_plan_empty_approach_rejected() {
        let raw = serde_json::to_string(&ImplementationPlan {
            approach: "  ".into(),
            steps: vec![PlanStep {
                description: "Do something".into(),
                file: None,
            }],
            target_files: vec![],
            risk: PlanRisk::Low,
        })
        .unwrap();

        assert!(validate_plan(&raw, 15).is_none());
    }

    #[test]
    fn test_validate_plan_malformed_json() {
        assert!(validate_plan("not json", 15).is_none());
        assert!(validate_plan("{}", 15).is_none());
    }

    #[test]
    fn test_plan_serde_roundtrip() {
        let plan = ImplementationPlan {
            approach: "Refactor module".into(),
            steps: vec![
                PlanStep {
                    description: "Extract function".into(),
                    file: Some("src/main.rs".into()),
                },
                PlanStep {
                    description: "Add tests".into(),
                    file: Some("tests/test.rs".into()),
                },
            ],
            target_files: vec!["src/main.rs".into(), "tests/test.rs".into()],
            risk: PlanRisk::Medium,
        };

        let json = serde_json::to_string_pretty(&plan).unwrap();
        let restored: ImplementationPlan = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.steps.len(), 2);
        assert_eq!(restored.risk, PlanRisk::Medium);
    }

    #[test]
    fn test_parse_file_line_arrow_format() {
        let (file, line) = parse_file_line("error[E0308]: mismatched types --> src/lib.rs:42:5");
        assert_eq!(file.as_deref(), Some("src/lib.rs"));
        assert_eq!(line, Some(42));
    }

    #[test]
    fn test_parse_file_line_colon_format() {
        let (file, line) = parse_file_line("src/main.rs:10:3: warning: unused variable");
        assert_eq!(file.as_deref(), Some("src/main.rs"));
        assert_eq!(line, Some(10));
    }

    #[test]
    fn test_parse_file_line_no_match() {
        let (file, line) = parse_file_line("some random error message");
        assert!(file.is_none());
        assert!(line.is_none());
    }

    #[test]
    fn test_apply_hints_to_packet_empty() {
        let mut packet = test_work_packet();
        apply_hints_to_packet(&mut packet, &[]);
        assert!(packet.relevant_heuristics.is_empty());
    }

    #[test]
    fn test_apply_hints_to_packet_with_hints() {
        let mut packet = test_work_packet();
        let hints = vec![
            VerifierHint {
                gate: "clippy".into(),
                message: "unused variable `x`".into(),
                file: Some("src/lib.rs".into()),
                line: Some(42),
            },
            VerifierHint {
                gate: "test".into(),
                message: "assertion failed".into(),
                file: None,
                line: None,
            },
        ];

        apply_hints_to_packet(&mut packet, &hints);
        assert_eq!(packet.relevant_heuristics.len(), 1);
        let hint_text = &packet.relevant_heuristics[0];
        assert!(hint_text.contains("Verifier Hints"));
        assert!(hint_text.contains("clippy"));
        assert!(hint_text.contains("src/lib.rs:42"));
        assert!(hint_text.contains("test"));
    }

    #[test]
    fn test_verifier_hint_serde_roundtrip() {
        let hint = VerifierHint {
            gate: "check".into(),
            message: "cannot find type `Foo`".into(),
            file: Some("src/bar.rs".into()),
            line: Some(15),
        };

        let json = serde_json::to_string(&hint).unwrap();
        let restored: VerifierHint = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.gate, "check");
        assert_eq!(restored.line, Some(15));
    }

    #[test]
    fn test_preflight_context_stages_tracked() {
        let packet = test_work_packet();
        let ctx = PreflightContext {
            harness: HarnessPolicy::derive(&packet, SwarmTier::Worker),
            packet,
            plan: None,
            verifier_hints: Vec::new(),
            kb_enriched: false,
            stages_run: vec!["context_packing".into(), "kb_enrichment".into()],
            acceptance_criteria: None,
        };

        assert_eq!(ctx.stages_run.len(), 2);
        assert!(ctx.stages_run.contains(&"context_packing".to_string()));
    }

    #[test]
    fn test_plan_risk_variants() {
        let risks = [PlanRisk::Low, PlanRisk::Medium, PlanRisk::High];
        for risk in risks {
            let json = serde_json::to_string(&risk).unwrap();
            let restored: PlanRisk = serde_json::from_str(&json).unwrap();
            assert_eq!(restored, risk);
        }
    }
}
